//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DiabloSdk
{
    [Serializable]
    public class OSDK_ACCLMsg : Message
    {
        public const string k_RosMessageName = "diablo_sdk/OSDK_ACCL";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float z;

        public OSDK_ACCLMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
        }

        public OSDK_ACCLMsg(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public static OSDK_ACCLMsg Deserialize(MessageDeserializer deserializer) => new OSDK_ACCLMsg(deserializer);

        private OSDK_ACCLMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
        }

        public override string ToString()
        {
            return "OSDK_ACCLMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
