//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DiabloSdk
{
    [Serializable]
    public class OSDK_POWERMsg : Message
    {
        public const string k_RosMessageName = "diablo_sdk/OSDK_POWER";
        public override string RosMessageName => k_RosMessageName;

        public float battery_voltage;
        public float battery_current;
        public float battery_capacitor_energy;
        public byte battery_power_percent;

        public OSDK_POWERMsg()
        {
            this.battery_voltage = 0.0f;
            this.battery_current = 0.0f;
            this.battery_capacitor_energy = 0.0f;
            this.battery_power_percent = 0;
        }

        public OSDK_POWERMsg(float battery_voltage, float battery_current, float battery_capacitor_energy, byte battery_power_percent)
        {
            this.battery_voltage = battery_voltage;
            this.battery_current = battery_current;
            this.battery_capacitor_energy = battery_capacitor_energy;
            this.battery_power_percent = battery_power_percent;
        }

        public static OSDK_POWERMsg Deserialize(MessageDeserializer deserializer) => new OSDK_POWERMsg(deserializer);

        private OSDK_POWERMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.battery_voltage);
            deserializer.Read(out this.battery_current);
            deserializer.Read(out this.battery_capacitor_energy);
            deserializer.Read(out this.battery_power_percent);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.battery_voltage);
            serializer.Write(this.battery_current);
            serializer.Write(this.battery_capacitor_energy);
            serializer.Write(this.battery_power_percent);
        }

        public override string ToString()
        {
            return "OSDK_POWERMsg: " +
            "\nbattery_voltage: " + battery_voltage.ToString() +
            "\nbattery_current: " + battery_current.ToString() +
            "\nbattery_capacitor_energy: " + battery_capacitor_energy.ToString() +
            "\nbattery_power_percent: " + battery_power_percent.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
