//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DiabloSdk
{
    [Serializable]
    public class OSDK_RCMsg : Message
    {
        public const string k_RosMessageName = "diablo_sdk/OSDK_RC";
        public override string RosMessageName => k_RosMessageName;

        public uint ch1;
        public uint ch2;
        public uint ch3;
        public uint ch4;
        public uint ch5;
        public uint ch6;
        public uint ch7;
        public uint ch8;
        public uint ch9;
        public uint ch10;
        public uint ch11;
        public uint ch12;
        public uint ch13;
        public uint ch14;
        public uint ch15;
        public uint ch16;
        public uint ch17;
        public uint ch18;
        public byte frame_lost;
        public byte failsafe;
        public byte reserve;

        public OSDK_RCMsg()
        {
            this.ch1 = 0;
            this.ch2 = 0;
            this.ch3 = 0;
            this.ch4 = 0;
            this.ch5 = 0;
            this.ch6 = 0;
            this.ch7 = 0;
            this.ch8 = 0;
            this.ch9 = 0;
            this.ch10 = 0;
            this.ch11 = 0;
            this.ch12 = 0;
            this.ch13 = 0;
            this.ch14 = 0;
            this.ch15 = 0;
            this.ch16 = 0;
            this.ch17 = 0;
            this.ch18 = 0;
            this.frame_lost = 0;
            this.failsafe = 0;
            this.reserve = 0;
        }

        public OSDK_RCMsg(uint ch1, uint ch2, uint ch3, uint ch4, uint ch5, uint ch6, uint ch7, uint ch8, uint ch9, uint ch10, uint ch11, uint ch12, uint ch13, uint ch14, uint ch15, uint ch16, uint ch17, uint ch18, byte frame_lost, byte failsafe, byte reserve)
        {
            this.ch1 = ch1;
            this.ch2 = ch2;
            this.ch3 = ch3;
            this.ch4 = ch4;
            this.ch5 = ch5;
            this.ch6 = ch6;
            this.ch7 = ch7;
            this.ch8 = ch8;
            this.ch9 = ch9;
            this.ch10 = ch10;
            this.ch11 = ch11;
            this.ch12 = ch12;
            this.ch13 = ch13;
            this.ch14 = ch14;
            this.ch15 = ch15;
            this.ch16 = ch16;
            this.ch17 = ch17;
            this.ch18 = ch18;
            this.frame_lost = frame_lost;
            this.failsafe = failsafe;
            this.reserve = reserve;
        }

        public static OSDK_RCMsg Deserialize(MessageDeserializer deserializer) => new OSDK_RCMsg(deserializer);

        private OSDK_RCMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ch1);
            deserializer.Read(out this.ch2);
            deserializer.Read(out this.ch3);
            deserializer.Read(out this.ch4);
            deserializer.Read(out this.ch5);
            deserializer.Read(out this.ch6);
            deserializer.Read(out this.ch7);
            deserializer.Read(out this.ch8);
            deserializer.Read(out this.ch9);
            deserializer.Read(out this.ch10);
            deserializer.Read(out this.ch11);
            deserializer.Read(out this.ch12);
            deserializer.Read(out this.ch13);
            deserializer.Read(out this.ch14);
            deserializer.Read(out this.ch15);
            deserializer.Read(out this.ch16);
            deserializer.Read(out this.ch17);
            deserializer.Read(out this.ch18);
            deserializer.Read(out this.frame_lost);
            deserializer.Read(out this.failsafe);
            deserializer.Read(out this.reserve);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ch1);
            serializer.Write(this.ch2);
            serializer.Write(this.ch3);
            serializer.Write(this.ch4);
            serializer.Write(this.ch5);
            serializer.Write(this.ch6);
            serializer.Write(this.ch7);
            serializer.Write(this.ch8);
            serializer.Write(this.ch9);
            serializer.Write(this.ch10);
            serializer.Write(this.ch11);
            serializer.Write(this.ch12);
            serializer.Write(this.ch13);
            serializer.Write(this.ch14);
            serializer.Write(this.ch15);
            serializer.Write(this.ch16);
            serializer.Write(this.ch17);
            serializer.Write(this.ch18);
            serializer.Write(this.frame_lost);
            serializer.Write(this.failsafe);
            serializer.Write(this.reserve);
        }

        public override string ToString()
        {
            return "OSDK_RCMsg: " +
            "\nch1: " + ch1.ToString() +
            "\nch2: " + ch2.ToString() +
            "\nch3: " + ch3.ToString() +
            "\nch4: " + ch4.ToString() +
            "\nch5: " + ch5.ToString() +
            "\nch6: " + ch6.ToString() +
            "\nch7: " + ch7.ToString() +
            "\nch8: " + ch8.ToString() +
            "\nch9: " + ch9.ToString() +
            "\nch10: " + ch10.ToString() +
            "\nch11: " + ch11.ToString() +
            "\nch12: " + ch12.ToString() +
            "\nch13: " + ch13.ToString() +
            "\nch14: " + ch14.ToString() +
            "\nch15: " + ch15.ToString() +
            "\nch16: " + ch16.ToString() +
            "\nch17: " + ch17.ToString() +
            "\nch18: " + ch18.ToString() +
            "\nframe_lost: " + frame_lost.ToString() +
            "\nfailsafe: " + failsafe.ToString() +
            "\nreserve: " + reserve.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
