//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DiabloSdk
{
    [Serializable]
    public class OSDK_QUATERNIONMsg : Message
    {
        public const string k_RosMessageName = "diablo_sdk/OSDK_QUATERNION";
        public override string RosMessageName => k_RosMessageName;

        public float w;
        public float x;
        public float y;
        public float z;

        public OSDK_QUATERNIONMsg()
        {
            this.w = 0.0f;
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
        }

        public OSDK_QUATERNIONMsg(float w, float x, float y, float z)
        {
            this.w = w;
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public static OSDK_QUATERNIONMsg Deserialize(MessageDeserializer deserializer) => new OSDK_QUATERNIONMsg(deserializer);

        private OSDK_QUATERNIONMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.w);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.w);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
        }

        public override string ToString()
        {
            return "OSDK_QUATERNIONMsg: " +
            "\nw: " + w.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
