// Generated by gencpp from file rviz_plugin_tutorials/ObstaclePose.msg
// DO NOT EDIT!


#ifndef RVIZ_PLUGIN_TUTORIALS_MESSAGE_OBSTACLEPOSE_H
#define RVIZ_PLUGIN_TUTORIALS_MESSAGE_OBSTACLEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace rviz_plugin_tutorials
{
template <class ContainerAllocator>
struct ObstaclePose_
{
  typedef ObstaclePose_<ContainerAllocator> Type;

  ObstaclePose_()
    : header()
    , pose()
    , shape()
    , angle()  {
    }
  ObstaclePose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)
    , shape(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _shape_type;
  _shape_type shape;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> const> ConstPtr;

}; // struct ObstaclePose_

typedef ::rviz_plugin_tutorials::ObstaclePose_<std::allocator<void> > ObstaclePose;

typedef boost::shared_ptr< ::rviz_plugin_tutorials::ObstaclePose > ObstaclePosePtr;
typedef boost::shared_ptr< ::rviz_plugin_tutorials::ObstaclePose const> ObstaclePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator1> & lhs, const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose == rhs.pose &&
    lhs.shape == rhs.shape &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator1> & lhs, const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rviz_plugin_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36863b4176c8b91be6f95b764a879c9d";
  }

  static const char* value(const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36863b4176c8b91bULL;
  static const uint64_t static_value2 = 0xe6f95b764a879c9dULL;
};

template<class ContainerAllocator>
struct DataType< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rviz_plugin_tutorials/ObstaclePose";
  }

  static const char* value(const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Vector3 pose\n"
"geometry_msgs/Vector3 shape\n"
"geometry_msgs/Vector3 angle\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
      stream.next(m.shape);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstaclePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rviz_plugin_tutorials::ObstaclePose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "shape: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.shape);
    s << indent << "angle: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVIZ_PLUGIN_TUTORIALS_MESSAGE_OBSTACLEPOSE_H
